---
extends: stylelint-config-standard
rules:
  selector-class-pattern:
    - "^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$"
    - message: Expected BEM naming convention for class.
